apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/overlays/infrastructure/infra/applications/traefik
  prune: true
  dependsOn: 
    - name: repositories-infra
    - name: cilium
  healthChecks:
    - kind: HelmRelease
      name: traefik
      namespace: traefik
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"