apiVersion: postgresql.cnpg.io/v1                                                                                                                                                                                                                                                       
kind: Cluster
metadata:
  name: immich-db
spec:
  instances: 2
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.4-v0.3.0
  superuserSecret:
    name: immich-pg-superuser
  enableSuperuserAccess: true
  startDelay: 30
  stopDelay: 100
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: restart ##@@ Cannot use switchover with 1 instance
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
    enableAlterSystem: true
  storage:
    size: 25Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      dataChecksums: true
      postInitApplicationSQL:
        # - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        # - SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube";
        - CREATE EXTENSION IF NOT EXISTS "earthdistance";
        - ALTER SCHEMA vectors OWNER TO "app";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vectors TO "app";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "app";
        # - CREATE EXTENSION IF NOT EXISTS "vector";
        - ALTER USER "app" WITH "superuser";
  # backup:
  #   retentionPolicy: "30d"
  #   barmanObjectStore:
  #     destinationPath: "s3://rke-cnpg-backups"
  #     endpointURL: "https://s3.example.com:443"
  #     endpointCA:
  #       name: ipa-ca
  #       key: ca-certificates.crt
  #     s3Credentials:
  #       accessKeyId: 
  #         name: s3-secret
  #         key: AWS_ACCESS_KEY_ID
  #       secretAccessKey: 
  #         name: s3-secret
  #         key: AWS_SECRET_ACCESS_KEY
