apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage-s3-store
spec:
  retentionPolicy: "30d"
  configuration:
    destinationPath: "s3://rke-cnpg-backups/"
    endpointURL: "https://s3.example.com"
    wal:
      compression: gzip
    s3Credentials:
      accessKeyId:
        name: s3-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: s3-secret
        key: ACCESS_SECRET_KEY
