apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mealie-db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  storage:
    size: 10Gi
  # plugins:
  # - name: barman-cloud.cloudnative-pg.io
  #   isWALArchiver: true
  #   parameters:
  #     barmanObjectName: garage-s3-store
