apiVersion: kustomize.config.k8s.io/v1beta1
namespace: flux-system
kind: Kustomization
resources:
- ashmantis.yaml
- bjw-s.yaml
- cilium.yaml
- cloudnative-pg.yaml
- csi-driver-nfs.yaml
- external-secrets.yaml
- ingress-nginx.yaml
- jetstack.yaml
- longhorn.yaml
- bitnami.yaml
- authelia.yaml
- dragonfly-operator.yaml
- gitlab.yaml
- victoria-metrics.yaml
- prometheus-community.yaml
- grafana.yaml
- requarks.yaml
- aka.yaml
- karakeep.yaml
- immich.yaml
- cowboysysop.yaml
- truecharts.yaml
- coder.yaml
- headlamp.yaml
- gabe565.yaml
- tika.yaml
- maikumori.yaml
- vyrtualsynthese.yaml
- stakater.yaml
- blocky.yaml
- external-dns.yaml
- traefik.yaml