apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example.com-tls
  namespace: traefik
spec:
  secretName: example.com-tls
  dnsNames:
    - example.com
    - '*.example.com'
    - '*.example.com'
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
