apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-secret
spec:
  refreshInterval: "15s"
  secretStoreRef: 
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oidc-secret
    creationPolicy: 'Owner'
  data:
  - secretKey: OIDC_CLIENT_ID
    remoteRef:
      key: authelia/clients/kubelogin
      property: id
  # - secretKey: OIDC_CLIENT_SECRET
  #   remoteRef:
  #     key: authelia/clients/kubelogin
  #     property: key
  - secretKey: OIDC_ISSUER_URL
    remoteRef:
      key: authelia/clients/headlamp
      property: url
  - secretKey: OIDC_SCOPES
    remoteRef:
      key: authelia/clients/headlamp
      property: scopes
