apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: freshrss-db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  storage:
    size: 10Gi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: garage-s3-store
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: freshrss-db-backup
spec:
  schedule: "0 0 4 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: freshrss-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io