apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-secret
  data:
  - secretKey: id
    remoteRef:
      key: coder/gitlab
      property: id
  - secretKey: secret
    remoteRef:
      key: coder/gitlab
      property: secret