apiVersion: v1
kind: Service
metadata:
  name: blocky-dns-external
spec:
  selector:
    app.kubernetes.io/name: blocky
    app.kubernetes.io/instance: blocky
    pod.name: main
  ports:
    - protocol: UDP
      name: dns-udp
      port: 53
      targetPort: 53
    - protocol: TCP
      name: dns-tco
      port: 53
      targetPort: 53
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: REDACTED_IP
